# Generated by Django 6.0.5 on 2026-06-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userlog",
            name="ip_address",
        ),
        migrations.AlterField(
            model_name="userlog",
            name="activity",
            field=models.CharField(max_length=50),
        ),
    ]
