# Generated by Django 6.0.5 on 2026-06-08 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("excel_ai_chatbot", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="created_at",
        ),
        migrations.AddField(
            model_name="student",
            name="excel_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="excel_ai_chatbot.excelupload",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="fee_status",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="student",
            name="remaining_fee",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="student",
            name="roll_no",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="total_paid_fee",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
