# Generated by Django 6.0.5 on 2026-06-08 07:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "excel_ai_chatbot",
            "0002_remove_student_created_at_student_excel_file_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="fee_status",
            field=models.CharField(
                choices=[("Paid", "Paid"), ("Pending", "Pending")],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="remaining_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="student",
            name="total_paid_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
